# Generated by Django 5.2.1 on 2025-05-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airquality',
            name='pm1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airquality',
            name='pm2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airquality',
            name='pm3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
